# Generated by Django 5.0.6 on 2024-06-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('location_frame', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'University Location',
                'verbose_name_plural': 'University Locations',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
